### ISSUE TITLE
Is it a pure Julia?

### ISSUE THREAD

**Issue by marcobonici** [LeeoBianchi/HealpixMPI.jl#8]
In the paper is writte
`Healpix.jl is a Julia-only implementation of the HEALPix [@HEALPix] library,`
My understanding, is that `Healpix.jl` is based on `Libsharp.jl`, that provides binding to the original `Libsharp` library. Is this right? If so, I would add this information, as it is true that the frontend is pure `Julia`, but the backend doing the heavy computations it is not.

**Comment by LeeoBianchi** [comment]
Hi @marcobonici ,

Please find below my explanation/reply to each of your comments.

> In the paper is writte `Healpix.jl is a Julia-only implementation of the HEALPix [@HEALPix] library,` 

Yes, and this definition is taken directly from Healpix.jl's [repository](https://github.com/ziotom78/Healpix.jl) as well as the title of it's paper. The reason to say so is that Healpix provides a wide variety of functionalities, besides the SHT which I focused on, which are entirely implemented in Julia in Healpix.jl. Moreover, Libsharp.jl relies on a JLL package which does not require any installation of C language nor any C library.  

> My understanding, is that `Healpix.jl` is based on `Libsharp.jl`, that provides binding to the original `Libsharp` library. Is this right? If so, I would add this information, as it is true that the frontend is pure `Julia`, but the backend doing the heavy computations it is not.

Yes, it is correct. And this is already stated in my paper in the "The latest SHT engine: DUCC".

Thank you,
Leo

**Comment by marcobonici** [comment]
Fine by me, thanks for the answer.
I am closing this issue.
