### ISSUE TITLE
Extend the context of the introduction

### ISSUE THREAD

**Issue by marcobonici** [LeeoBianchi/HealpixMPI.jl#9]
While the author is mostly working on CMB (and of course the code developed here is relevant in this context!) I think it would be interesting to add a bit more context. Also people working in the field of the Large-Scale-Structure of the universe (as myself!) use SHT a lot and should find your paper interesting (spoiler: I do, I am even using `Healpix.jl` now!).
Add a couple of papers employing SHT in LSS.

**Comment by LeeoBianchi** [comment]
> While the author is mostly working on CMB (and of course the code developed here is relevant in this context!) I think it would be interesting to add a bit more context. Also people working in the field of the Large-Scale-Structure of the universe (as myself!) use SHT a lot and should find your paper interesting (spoiler: I do, I am even using `Healpix.jl` now!). Add a couple of papers employing SHT in LSS.

Good point! Since you work in the LSS field, do you have any suggestion for such papers to reference to?

Ciao!
Leo

**Comment by marcobonici** [comment]
Here is a recent one
[Luoreiro et al](https://arxiv.org/abs/2210.13260)

**Comment by LeeoBianchi** [comment]
Ciao @marcobonici 

Please find an updated version of the paper with the citation you recommended + one from Euclid angular power spectrum estimation I found.
Let me know if you think it works now.

**Comment by marcobonici** [comment]
Fine by me, I will close the issue.
